layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: true
    projects:
    # - repo-name

social_media:
  facebook: nparsons08
  instagram: _nickparsons_
  linkedin: nparsons
  medium: nparsons08
  stackoverflow: 638080
  twitter: nickparsons
  website: https://nickparsons.io

topics:
  - name: Algolia
    web_url: https://github.com/topics/algolia
    image_url: https://raw.githubusercontent.com/github/explore/ef2e43512bb3fb76803e5cda99a87bcc4b601b7a/topics/algolia/algolia.png

  - name: AWS
    web_url: https://github.com/topics/aws
    image_url: https://raw.githubusercontent.com/github/explore/9f270b9ddad21705ebd33f4602a0aec0d22cbe4e/topics/aws/aws.png

  - name: Google Cloud Platform
    web_url: https://github.com/topics/google-cloud-platform
    image_url: https://raw.githubusercontent.com/github/explore/9f270b9ddad21705ebd33f4602a0aec0d22cbe4e/topics/google/google.png

  - name: Docker
    web_url: https://github.com/topics/docker
    image_url: https://raw.githubusercontent.com/github/explore/9f270b9ddad21705ebd33f4602a0aec0d22cbe4e/topics/docker/docker.png

  - name: Kubernetes
    web_url: https://github.com/topics/kubernetes
    image_url: https://raw.githubusercontent.com/github/explore/9f270b9ddad21705ebd33f4602a0aec0d22cbe4e/topics/kubernetes/kubernetes.png

  - name: Express
    web_url: https://github.com/topics/express
    image_url: https://raw.githubusercontent.com/github/explore/9f270b9ddad21705ebd33f4602a0aec0d22cbe4e/topics/express/express.png

  - name: Git
    web_url: https://github.com/topics/git
    image_url: https://raw.githubusercontent.com/github/explore/9f270b9ddad21705ebd33f4602a0aec0d22cbe4e/topics/git/git.png

  - name: GraphQL
    web_url: https://github.com/topics/graphql
    image_url: https://raw.githubusercontent.com/github/explore/9f270b9ddad21705ebd33f4602a0aec0d22cbe4e/topics/graphql/graphql.png

  - name: Netlify
    web_url: https://github.com/topics/netlify
    image_url: https://avatars0.githubusercontent.com/u/7892489?s=200&v=4

  - name: Gatsby
    web_url: https://github.com/topics/gatsby
    image_url: https://avatars1.githubusercontent.com/u/12551863?s=200&v=4

  - name: JavaScript
    web_url: https://github.com/topics/javascript
    image_url: https://raw.githubusercontent.com/github/explore/9f270b9ddad21705ebd33f4602a0aec0d22cbe4e/topics/javascript/javascript.png

  - name: Apollo GraphQL
    web_url: https://github.com/topics/apollographql
    image_url: https://avatars2.githubusercontent.com/u/17189275?s=200&v=4

  - name: MongoDB
    web_url: https://github.com/topics/mongodb
    image_url: https://raw.githubusercontent.com/github/explore/9f270b9ddad21705ebd33f4602a0aec0d22cbe4e/topics/mongodb/mongodb.png

  - name: Mongoose
    web_url: https://github.com/topics/mongoose
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/mongoose/mongoose.png

  - name: Node
    web_url: https://github.com/topics/node
    image_url: https://raw.githubusercontent.com/github/explore/9f270b9ddad21705ebd33f4602a0aec0d22cbe4e/topics/nodejs/nodejs.png

  - name: PostgreSQL
    web_url: https://github.com/topics/postgresql
    image_url: https://raw.githubusercontent.com/github/explore/9f270b9ddad21705ebd33f4602a0aec0d22cbe4e/topics/postgresql/postgresql.png

  - name: React
    web_url: https://github.com/topics/react
    image_url: https://raw.githubusercontent.com/github/explore/9f270b9ddad21705ebd33f4602a0aec0d22cbe4e/topics/react-native/react-native.png

  - name: React Native
    web_url: https://github.com/topics/react-native
    image_url: https://raw.githubusercontent.com/github/explore/9f270b9ddad21705ebd33f4602a0aec0d22cbe4e/topics/react-native/react-native.png

  - name: Redux
    web_url: https://github.com/topics/redux
    image_url: https://raw.githubusercontent.com/github/explore/9f270b9ddad21705ebd33f4602a0aec0d22cbe4e/topics/redux/redux.png

  - name: Serverless
    web_url: https://github.com/topics/serverless
    image_url: https://avatars1.githubusercontent.com/u/13742415?s=400&v=4

certifications:
  - name: MongoDB for Node.js Developers
    web_url: https://university.mongodb.com/
    image_url: https://raw.githubusercontent.com/github/explore/9f270b9ddad21705ebd33f4602a0aec0d22cbe4e/topics/mongodb/mongodb.png

  - name: MongoDB for DBAs
    web_url: https://university.mongodb.com/
    image_url: https://raw.githubusercontent.com/github/explore/9f270b9ddad21705ebd33f4602a0aec0d22cbe4e/topics/mongodb/mongodb.png
